# Generated by Django 3.2.16 on 2023-03-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
